# Generated by Django 4.2.9 on 2024-02-25 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.TextField(default='Beethoven', max_length=30),
        ),
    ]
